// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTicket(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateTicket'](arg1, arg2, arg3);
}

export function GetAllTickets() {
  return window['go']['backend']['App']['GetAllTickets']();
}

export function GetMe() {
  return window['go']['backend']['App']['GetMe']();
}

export function Login(arg1, arg2) {
  return window['go']['backend']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['backend']['App']['Register'](arg1, arg2);
}

export function UpdateTicketStatus(arg1, arg2) {
  return window['go']['backend']['App']['UpdateTicketStatus'](arg1, arg2);
}
