// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateTicket(arg1:string,arg2:string,arg3:number):Promise<backend.Ticket>;

export function GetAllTickets():Promise<Array<backend.Ticket>>;

export function GetMe():Promise<backend.User>;

export function Login(arg1:string,arg2:string):Promise<backend.User>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<string>;

export function UpdateTicketStatus(arg1:number,arg2:backend.TicketStatus):Promise<void>;
