// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetMe():Promise<backend.User>;

export function Login(arg1:string,arg2:string):Promise<backend.User>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<string>;
